### ISSUE TITLE
Ambiguity in testing errors

### ISSUE THREAD

**Issue by ps-video-player** [orourkedd/effects-as-data#17]
How does test runner know if the value in a test tuple is an error?  How does it compare this error to an error/value thrown from the function?  How does the test runner handle an error in a test tuple?

**Comment by ps-video-player** [comment]
Also, add a success boolean to the `onComplete` callback to know if the function errorred out.

**Comment by michaeljacobdavis** [comment]
Just to refresh my memory on this. The issue is the test runner handles `Error` values differently than normal values so throwing a non-error wouldn't test correctly and similarly returning an error (without throwing) from a handler wouldn't work?

**Comment by orourkedd** [comment]
Correct

**Comment by orourkedd** [comment]
As long as functions don't return errors and code doesn't throw non-errors, everything should work.    Because returning errors and throwing non-errors are anti-patterns, I think these constraints are acceptable for now.
